trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/HyperMsg.csproj'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'
