name: HyperMsg.Core
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: src/**/*.csproj
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: test/**/*.csproj