name: HyperMsg.Core
jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
    - task: DotNetCoreCLI@2
      name: build
      displayName: Build
      inputs:
        command: build
        projects: src/**/*.csproj

    - task: DotNetCoreCLI@2
      name: test
      displayName: Test
      inputs:
        command: test
        projects: test/**/*.csproj
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'src'
        Contents: '**/*.dll'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@0
      name: PublishPipelineArtifacts
      displayName: Publish pipeline artifacts      
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'

- job: publish
  displayName: 'Publish package'
  dependsOn: BuildAndTest
  steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        
    - task: DotNetCoreCLI@2
      name: pack
      displayName: 'Create NuGet package'
      inputs:
        command: 'pack'
        searchPatternPack: 'src/**/*.csproj'
        nobuild: true
        majorVersion: 0
        minorVersion: 0
        patchVersion: $(Build.BuildId)
        versioningScheme: byPrereleaseNumber