name: HyperMsg.Core
steps:
  - task: DotNetCoreCLI@2
    name: build
    displayName: Build
    inputs:
      command: build
      projects: src/**/*.csproj
  - task: DotNetCoreCLI@2
    name: test
    displayName: Test
    inputs:
      command: test
      projects: test/**/*.csproj
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'HyperMsg.Core'
      publishLocation: 'pipeline'