name: HyperMsg.Core
steps:
  - task: DotNetCoreCLI@2
    name: build
    displayName: Build
    inputs:
      command: build
      projects: src/**/*.csproj
  - task: DotNetCoreCLI@2
    name: test
    displayName: Test
    inputs:
      command: test
      projects: test/**/*.csproj
  - task: PublishTestResults@2
    name: publish_test_results
    displayName: 'Publish test results'
    inputs:
      testRunner: 'XUnit'
  - task: DotNetCoreCLI@2
    name: pack
    displayName: Pack
    inputs:      
      command: pack
      searchPatternPack: 'src/**/*.csproj'
  - task: DotNetCoreCLI@2
    name: publish
    displayName: Publish
    inputs:
      command: 'push'
      feedPublish: 'HyperMsg'
      versioningScheme: byPrereleaseNumber