name: HyperMsg.Core
jobs:
  - job: BuildAndTest
    steps:
      - task: DotNetCoreCLI@2
        name: build
        displayName: Build
        inputs:
          command: build
          projects: src/**/*.csproj
          
      - task: DotNetCoreCLI@2
        name: test
        displayName: Test
        inputs:
          command: test
          projects: test/**/*.csproj

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.BinariesDirectory)'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          ArtifactName: 'drop'