name: Publish package
on: 
  workflow_dispatch:
    inputs:
      package_version:
        description: Package version
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/BuzzX8/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create the package
        run: dotnet pack -c Release -o ./packages -p:PackageVersion=${{ github.event.inputs.package_version }}
      - name: Publish the package to GPR
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}