name: Publish package
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet build -c Release
      - name: Create the package
        run: dotnet pack -c Release
      - name: Publish the package to GPR
        run: dotnet nuget push ./bin/Release/*.nupkg